project_id = "vuawmihxcaewzmkuarkr"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-notification]
    verify_jwt = false
  [functions.session-reminders-cron]
    verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
