import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { z } from "https://deno.land/x/zod@v3.22.4/mod.ts";
import { jsPDF } from "https://esm.sh/jspdf@2.5.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const BodySchema = z.object({
  transactionId: z.string().uuid(),
  outcome: z.enum(["succeeded", "failed"]).default("succeeded"),
  failureReason: z.string().optional(),
});

async function generateInvoicePdf(opts: {
  invoiceNumber: string;
  amountMad: number;
  transactionType: string;
  patientName: string;
  psychologistName: string;
  paidAt: string;
}): Promise<Uint8Array> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const maroon = "#6B1F2A";
  const gold = "#C8A96A";

  // Header band
  doc.setFillColor(maroon);
  doc.rect(0, 0, 595, 90, "F");
  doc.setTextColor("#FFFFFF");
  doc.setFontSize(22);
  doc.text("U.Psy", 40, 50);
  doc.setFontSize(11);
  doc.text("Performance Psychology System", 40, 68);

  // Invoice meta
  doc.setTextColor("#1a1a1a");
  doc.setFontSize(18);
  doc.text("INVOICE", 40, 140);
  doc.setFontSize(10);
  doc.text(`Invoice #: ${opts.invoiceNumber}`, 40, 162);
  doc.text(`Date: ${new Date(opts.paidAt).toLocaleDateString("en-GB")}`, 40, 178);

  // Bill to
  doc.setFontSize(11);
  doc.setTextColor(maroon);
  doc.text("Billed to", 40, 220);
  doc.setTextColor("#1a1a1a");
  doc.setFontSize(10);
  doc.text(opts.patientName || "Client", 40, 238);

  // Items
  doc.setDrawColor(gold);
  doc.setLineWidth(0.5);
  doc.line(40, 290, 555, 290);
  doc.setFontSize(10);
  doc.setTextColor("#666");
  doc.text("Description", 40, 308);
  doc.text("Amount", 480, 308);
  doc.line(40, 318, 555, 318);

  doc.setTextColor("#1a1a1a");
  doc.setFontSize(11);
  const desc = `${opts.transactionType === "deposit" ? "Session deposit" : "Session payment"} — ${opts.psychologistName}`;
  doc.text(desc, 40, 340);
  doc.text(`${opts.amountMad.toFixed(2)} MAD`, 480, 340);

  doc.line(40, 360, 555, 360);
  doc.setFontSize(13);
  doc.setTextColor(maroon);
  doc.text("Total", 400, 384);
  doc.text(`${opts.amountMad.toFixed(2)} MAD`, 480, 384);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor("#999");
  doc.text("Test invoice — generated by U.Psy in test payment mode.", 40, 780);
  doc.text("U.Psy · upsy.ma · contact@upsy.ma", 40, 794);

  return new Uint8Array(doc.output("arraybuffer"));
}

function nextInvoiceNumber(): string {
  const d = new Date();
  const y = d.getUTCFullYear();
  const ts = Date.now().toString(36).toUpperCase();
  return `UPSY-${y}-${ts}`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      { global: { headers: { Authorization: authHeader } } },
    );
    const token = authHeader.replace("Bearer ", "");
    const { data: claims, error: claimsErr } = await supabase.auth.getClaims(token);
    if (claimsErr || !claims?.claims) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const userId = claims.claims.sub as string;

    const parsed = BodySchema.safeParse(await req.json());
    if (!parsed.success) {
      return new Response(JSON.stringify({ error: parsed.error.flatten() }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const { transactionId, outcome, failureReason } = parsed.data;

    const admin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    );
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
    const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

    const { data: tx, error: txErr } = await admin
      .from("payment_transactions")
      .select("*")
      .eq("id", transactionId)
      .single();
    if (txErr || !tx) {
      return new Response(JSON.stringify({ error: "Transaction not found" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (tx.patient_id !== userId) {
      return new Response(JSON.stringify({ error: "Forbidden" }), {
        status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (tx.status !== "pending") {
      return new Response(JSON.stringify({ error: `Transaction already ${tx.status}` }), {
        status: 409, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const now = new Date().toISOString();

    if (outcome === "succeeded") {
      // Generate invoice PDF (best-effort)
      let invoiceNumber: string | null = null;
      let invoicePath: string | null = null;
      try {
        invoiceNumber = nextInvoiceNumber();

        const [{ data: patientProfile }, { data: psyProfile }] = await Promise.all([
          admin.from("profiles").select("full_name").eq("id", tx.patient_id).maybeSingle(),
          admin.from("psychologist_profiles").select("full_name").eq("id", tx.psychologist_id).maybeSingle(),
        ]);

        const pdfBytes = await generateInvoicePdf({
          invoiceNumber,
          amountMad: Number(tx.amount_mad ?? 0),
          transactionType: tx.transaction_type ?? "payment",
          patientName: patientProfile?.full_name ?? "Client",
          psychologistName: psyProfile?.full_name ?? "Specialist",
          paidAt: now,
        });

        const path = `${tx.patient_id}/invoices/${invoiceNumber}.pdf`;
        const { error: upErr } = await admin.storage
          .from("user-documents")
          .upload(path, pdfBytes, { contentType: "application/pdf", upsert: true });
        if (upErr) {
          console.error("invoice upload failed:", upErr.message);
        } else {
          invoicePath = path;
        }
      } catch (e) {
        console.error("invoice generation failed:", e);
      }

      await admin
        .from("payment_transactions")
        .update({
          status: "succeeded",
          paid_at: now,
          invoice_number: invoiceNumber,
          invoice_pdf_url: invoicePath,
        })
        .eq("id", transactionId);

      // Confirm booking
      await admin
        .from("bookings")
        .update({
          status: "confirmed",
          payment_status: tx.transaction_type === "deposit" ? "deposit_paid" : "paid",
        })
        .eq("id", tx.booking_id);

      // Fire-and-forget notifications (don't block response)
      const notifyUrl = `${SUPABASE_URL}/functions/v1/send-notification`;
      const headers = {
        "Content-Type": "application/json",
        Authorization: `Bearer ${SERVICE_ROLE}`,
      };
      const amountMAD = Number(tx.amount_mad).toLocaleString();
      Promise.all([
        fetch(notifyUrl, {
          method: "POST",
          headers,
          body: JSON.stringify({
            user_id: tx.patient_id,
            type: "payment_succeeded",
            title: "Payment received",
            body: `Your payment of ${amountMAD} MAD was successful. Invoice ${invoiceNumber} is ready.`,
            action_url: "/my-space",
            send_email: true,
            metadata: { transaction_id: transactionId, invoice_number: invoiceNumber },
          }),
        }),
        fetch(notifyUrl, {
          method: "POST",
          headers,
          body: JSON.stringify({
            user_id: tx.psychologist_id,
            type: "booking_confirmed",
            title: "New paid session",
            body: `A client just paid ${amountMAD} MAD. The session is confirmed.`,
            action_url: "/dashboard/specialist",
            send_email: true,
            metadata: { booking_id: tx.booking_id },
          }),
        }),
      ]).catch((e) => console.error("notify error", e));

      return new Response(
        JSON.stringify({
          success: true,
          status: "succeeded",
          bookingConfirmed: true,
          invoiceNumber,
          invoicePath,
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    } else {
      await admin
        .from("payment_transactions")
        .update({ status: "failed", failure_reason: failureReason ?? "Mock payment failed" })
        .eq("id", transactionId);

      await admin
        .from("bookings")
        .update({ status: "cancelled", payment_status: "failed" })
        .eq("id", tx.booking_id);

      // Notify patient of failure
      fetch(`${SUPABASE_URL}/functions/v1/send-notification`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${SERVICE_ROLE}`,
        },
        body: JSON.stringify({
          user_id: tx.patient_id,
          type: "payment_succeeded",
          title: "Payment failed",
          body: failureReason ?? "Your payment could not be processed. Please try again.",
          action_url: "/my-space",
          send_email: false,
        }),
      }).catch((e) => console.error("notify error", e));

      return new Response(
        JSON.stringify({ success: true, status: "failed" }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }
  } catch (err) {
    console.error("simulate-payment-webhook error:", err);
    return new Response(JSON.stringify({ error: "Internal error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});