CREATE OR REPLACE FUNCTION public.bookings_patient_insert_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  -- Admins and the psychologist-side proposal flow keep their behaviour.
  IF public.has_role(auth.uid(), 'admin'::app_role) THEN
    RETURN NEW;
  END IF;
  IF auth.uid() = NEW.psychologist_id THEN
    RETURN NEW;
  END IF;
  IF auth.uid() IS DISTINCT FROM NEW.patient_id THEN
    RETURN NEW; -- other paths (service role / RLS) unaffected
  END IF;

  -- Patient path: strip server-controlled columns at insert time, mirroring
  -- the restrictions enforced by bookings_patient_update_guard on UPDATE.
  NEW.proposal_token := NULL;
  NEW.proposal_expires_at := NULL;
  NEW.proposed_by := NULL;
  NEW.video_room_id := NULL; -- regenerated by set_booking_video_room
  NEW.payment_status := COALESCE(NEW.payment_status, 'unpaid');
  NEW.status := 'pending';

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS bookings_patient_insert_guard_trg ON public.bookings;
CREATE TRIGGER bookings_patient_insert_guard_trg
BEFORE INSERT ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.bookings_patient_insert_guard();