// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Load-bearing for OAuth, and stated explicitly rather than left to the
    // default. Google and Apple sign-in return the user to the site with the
    // session in the URL; this is what reads it and establishes the session.
    // It defaults to true, so omitting it works — right up until someone sets
    // it to false for an unrelated reason and social sign-in silently stops
    // completing, with no error and no failed request to point at.
    detectSessionInUrl: true,
  }
});